/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const AttendanceRecord = IDL.Record({
  'memberId' : IDL.Principal,
  'checkInTime' : Time,
  'checkOutTime' : IDL.Opt(Time),
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'booked' : IDL.Null,
});
export const ClassType = IDL.Variant({
  'yoga' : IDL.Null,
  'crossfit' : IDL.Null,
  'zumba' : IDL.Null,
  'pilates' : IDL.Null,
});
export const ClassBooking = IDL.Record({
  'id' : IDL.Text,
  'status' : BookingStatus,
  'memberId' : IDL.Principal,
  'date' : Time,
  'classType' : ClassType,
});
export const ExpenseType = IDL.Variant({
  'other' : IDL.Null,
  'equipment' : IDL.Null,
  'rent' : IDL.Null,
  'utilities' : IDL.Null,
});
export const Expense = IDL.Record({
  'id' : IDL.Text,
  'type' : ExpenseType,
  'description' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const Credentials = IDL.Record({
  'password' : IDL.Text,
  'email' : IDL.Text,
});
export const MembershipPlan = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'durationMonths' : IDL.Nat,
  'benefits' : IDL.Text,
  'price' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ManualCreateMemberRequest = IDL.Record({
  'name' : IDL.Text,
  'credentials' : Credentials,
  'phone' : IDL.Text,
  'membershipPlan' : MembershipPlan,
  'profilePic' : IDL.Opt(ExternalBlob),
});
export const MembershipStatus = IDL.Variant({
  'active' : IDL.Null,
  'expired' : IDL.Null,
  'pending' : IDL.Null,
});
export const Meal = IDL.Record({
  'fatG' : IDL.Nat,
  'calories' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'carbsG' : IDL.Nat,
  'proteinG' : IDL.Nat,
});
export const DietPlan = IDL.Record({
  'id' : IDL.Text,
  'meals' : IDL.Vec(Meal),
  'fatG' : IDL.Nat,
  'calories' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'carbsG' : IDL.Nat,
  'proteinG' : IDL.Nat,
});
export const Exercise = IDL.Record({
  'name' : IDL.Text,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'weightKg' : IDL.Nat,
});
export const WorkoutPlan = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'exercises' : IDL.Vec(Exercise),
  'description' : IDL.Text,
  'durationWeeks' : IDL.Nat,
});
export const MemberProfile = IDL.Record({
  'id' : IDL.Nat,
  'principal' : IDL.Principal,
  'endDate' : Time,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'membershipStatus' : MembershipStatus,
  'phone' : IDL.Text,
  'dietPlan' : IDL.Opt(DietPlan),
  'membershipPlan' : MembershipPlan,
  'profilePic' : IDL.Opt(ExternalBlob),
  'workoutPlan' : IDL.Opt(WorkoutPlan),
  'startDate' : Time,
});
export const CommunicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'sent' : IDL.Null,
  'failed' : IDL.Null,
});
export const CommunicationChannel = IDL.Variant({
  'sms' : IDL.Null,
  'whatsapp' : IDL.Null,
  'email' : IDL.Null,
});
export const CommunicationLogEntry = IDL.Record({
  'status' : CommunicationStatus,
  'content' : IDL.Text,
  'timestamp' : Time,
  'channel' : CommunicationChannel,
});
export const ManualCreateMemberResponse = IDL.Record({
  'member' : MemberProfile,
  'credentials' : Credentials,
  'communicationLogs' : IDL.Vec(CommunicationLogEntry),
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'failed' : IDL.Null,
});
export const Payment = IDL.Record({
  'id' : IDL.Text,
  'status' : PaymentStatus,
  'memberId' : IDL.Principal,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const CreateMemberRequest = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
  'membershipPlan' : MembershipPlan,
  'profilePic' : IDL.Opt(ExternalBlob),
});
export const MemberCredentials = IDL.Record({
  'password' : IDL.Text,
  'email' : IDL.Text,
});
export const CreateMemberResponse = IDL.Record({
  'member' : MemberProfile,
  'credentials' : MemberCredentials,
  'communicationLogs' : IDL.Vec(CommunicationLogEntry),
});
export const MinimalMember = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const AppRole = IDL.Variant({ 'Member' : IDL.Null, 'Admin' : IDL.Null });
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'role' : AppRole,
  'email' : IDL.Text,
  'profilePic' : IDL.Opt(ExternalBlob),
});
export const Notification = IDL.Record({
  'title' : IDL.Text,
  'icon' : IDL.Text,
  'color' : IDL.Text,
  'actions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'message' : IDL.Text,
  'timestamp' : Time,
  'priority' : IDL.Nat,
});
export const RegisteredMemberInfo = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const ReportMember = IDL.Record({
  'member' : MemberProfile,
  'isExpired' : IDL.Bool,
  'moneyDue' : IDL.Nat,
  'isExpiringSoon' : IDL.Bool,
});
export const ReportSummary = IDL.Record({
  'members' : IDL.Vec(ReportMember),
  'totalPayments' : IDL.Nat,
  'totalExpenses' : IDL.Nat,
  'profit' : IDL.Nat,
  'monthlyRevenue' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const SerializeMemberProfile = IDL.Record({
  'id' : IDL.Text,
  'principal' : IDL.Text,
  'endDate' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'membershipStatus' : MembershipStatus,
  'phone' : IDL.Text,
  'dietPlan' : IDL.Opt(DietPlan),
  'membershipPlan' : MembershipPlan,
  'profilePic' : IDL.Opt(ExternalBlob),
  'workoutPlan' : IDL.Opt(WorkoutPlan),
  'startDate' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAttendance' : IDL.Func([AttendanceRecord], [], []),
  'addClassBooking' : IDL.Func([ClassBooking], [], []),
  'addExpense' : IDL.Func([Expense], [], []),
  'addMember' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'addMemberWithManualCredentials' : IDL.Func(
      [ManualCreateMemberRequest],
      [ManualCreateMemberResponse],
      [],
    ),
  'addMembershipPlan' : IDL.Func([MembershipPlan], [], []),
  'addPayment' : IDL.Func([Payment], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkIn' : IDL.Func([], [AttendanceRecord], []),
  'checkOut' : IDL.Func([], [AttendanceRecord], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createMemberWithCredentials' : IDL.Func(
      [CreateMemberRequest],
      [CreateMemberResponse],
      [],
    ),
  'deleteMember' : IDL.Func([IDL.Nat], [], []),
  'deleteMembershipPlan' : IDL.Func([IDL.Text], [], []),
  'generateQrCode' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'getAllCommunicationLogs' : IDL.Func(
      [],
      [IDL.Vec(CommunicationLogEntry)],
      ['query'],
    ),
  'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getAllMembers' : IDL.Func([], [IDL.Vec(MemberProfile)], ['query']),
  'getAllMembershipPlans' : IDL.Func([], [IDL.Vec(MembershipPlan)], ['query']),
  'getAllMinimalMembers' : IDL.Func([], [IDL.Vec(MinimalMember)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getAttendanceByMember' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceByMemberStatus' : IDL.Func(
      [MembershipStatus],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClassBookingsByStatus' : IDL.Func(
      [BookingStatus],
      [IDL.Vec(ClassBooking)],
      ['query'],
    ),
  'getCommunicationLogsByEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CommunicationLogEntry)],
      ['query'],
    ),
  'getMember' : IDL.Func([IDL.Nat], [MemberProfile], ['query']),
  'getMemberAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
  'getMemberClassBookings' : IDL.Func([], [IDL.Vec(ClassBooking)], ['query']),
  'getMemberNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getMemberPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getMemberProfile' : IDL.Func([], [IDL.Opt(MemberProfile)], ['query']),
  'getMembershipPlan' : IDL.Func([IDL.Text], [MembershipPlan], ['query']),
  'getMyQrCode' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getPayment' : IDL.Func([IDL.Text], [Payment], ['query']),
  'getRegisteredMembers' : IDL.Func(
      [],
      [IDL.Vec(RegisteredMemberInfo)],
      ['query'],
    ),
  'getReports' : IDL.Func([], [ReportSummary], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([IDL.Principal], [UserRole], ['query']),
  'isAdminRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'logCommunication' : IDL.Func(
      [IDL.Text, CommunicationChannel, IDL.Text, CommunicationStatus],
      [],
      [],
    ),
  'memberLogin' : IDL.Func([IDL.Text, IDL.Text], [SerializeMemberProfile], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateClassBooking' : IDL.Func([IDL.Text, ClassBooking], [], []),
  'updateMember' : IDL.Func([IDL.Nat, MemberProfile], [], []),
  'updateMemberDietPlan' : IDL.Func([IDL.Nat, DietPlan], [], []),
  'updateMemberProfile' : IDL.Func([MemberProfile], [], []),
  'updateMemberWorkoutPlan' : IDL.Func([IDL.Nat, WorkoutPlan], [], []),
  'updateMembershipPlan' : IDL.Func([MembershipPlan], [], []),
  'validateQrCode' : IDL.Func([IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const AttendanceRecord = IDL.Record({
    'memberId' : IDL.Principal,
    'checkInTime' : Time,
    'checkOutTime' : IDL.Opt(Time),
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'booked' : IDL.Null,
  });
  const ClassType = IDL.Variant({
    'yoga' : IDL.Null,
    'crossfit' : IDL.Null,
    'zumba' : IDL.Null,
    'pilates' : IDL.Null,
  });
  const ClassBooking = IDL.Record({
    'id' : IDL.Text,
    'status' : BookingStatus,
    'memberId' : IDL.Principal,
    'date' : Time,
    'classType' : ClassType,
  });
  const ExpenseType = IDL.Variant({
    'other' : IDL.Null,
    'equipment' : IDL.Null,
    'rent' : IDL.Null,
    'utilities' : IDL.Null,
  });
  const Expense = IDL.Record({
    'id' : IDL.Text,
    'type' : ExpenseType,
    'description' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const Credentials = IDL.Record({ 'password' : IDL.Text, 'email' : IDL.Text });
  const MembershipPlan = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'durationMonths' : IDL.Nat,
    'benefits' : IDL.Text,
    'price' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ManualCreateMemberRequest = IDL.Record({
    'name' : IDL.Text,
    'credentials' : Credentials,
    'phone' : IDL.Text,
    'membershipPlan' : MembershipPlan,
    'profilePic' : IDL.Opt(ExternalBlob),
  });
  const MembershipStatus = IDL.Variant({
    'active' : IDL.Null,
    'expired' : IDL.Null,
    'pending' : IDL.Null,
  });
  const Meal = IDL.Record({
    'fatG' : IDL.Nat,
    'calories' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'carbsG' : IDL.Nat,
    'proteinG' : IDL.Nat,
  });
  const DietPlan = IDL.Record({
    'id' : IDL.Text,
    'meals' : IDL.Vec(Meal),
    'fatG' : IDL.Nat,
    'calories' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'carbsG' : IDL.Nat,
    'proteinG' : IDL.Nat,
  });
  const Exercise = IDL.Record({
    'name' : IDL.Text,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'weightKg' : IDL.Nat,
  });
  const WorkoutPlan = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'exercises' : IDL.Vec(Exercise),
    'description' : IDL.Text,
    'durationWeeks' : IDL.Nat,
  });
  const MemberProfile = IDL.Record({
    'id' : IDL.Nat,
    'principal' : IDL.Principal,
    'endDate' : Time,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'membershipStatus' : MembershipStatus,
    'phone' : IDL.Text,
    'dietPlan' : IDL.Opt(DietPlan),
    'membershipPlan' : MembershipPlan,
    'profilePic' : IDL.Opt(ExternalBlob),
    'workoutPlan' : IDL.Opt(WorkoutPlan),
    'startDate' : Time,
  });
  const CommunicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'sent' : IDL.Null,
    'failed' : IDL.Null,
  });
  const CommunicationChannel = IDL.Variant({
    'sms' : IDL.Null,
    'whatsapp' : IDL.Null,
    'email' : IDL.Null,
  });
  const CommunicationLogEntry = IDL.Record({
    'status' : CommunicationStatus,
    'content' : IDL.Text,
    'timestamp' : Time,
    'channel' : CommunicationChannel,
  });
  const ManualCreateMemberResponse = IDL.Record({
    'member' : MemberProfile,
    'credentials' : Credentials,
    'communicationLogs' : IDL.Vec(CommunicationLogEntry),
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Payment = IDL.Record({
    'id' : IDL.Text,
    'status' : PaymentStatus,
    'memberId' : IDL.Principal,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const CreateMemberRequest = IDL.Record({
    'name' : IDL.Text,
    'phone' : IDL.Text,
    'membershipPlan' : MembershipPlan,
    'profilePic' : IDL.Opt(ExternalBlob),
  });
  const MemberCredentials = IDL.Record({
    'password' : IDL.Text,
    'email' : IDL.Text,
  });
  const CreateMemberResponse = IDL.Record({
    'member' : MemberProfile,
    'credentials' : MemberCredentials,
    'communicationLogs' : IDL.Vec(CommunicationLogEntry),
  });
  const MinimalMember = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const AppRole = IDL.Variant({ 'Member' : IDL.Null, 'Admin' : IDL.Null });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'role' : AppRole,
    'email' : IDL.Text,
    'profilePic' : IDL.Opt(ExternalBlob),
  });
  const Notification = IDL.Record({
    'title' : IDL.Text,
    'icon' : IDL.Text,
    'color' : IDL.Text,
    'actions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'message' : IDL.Text,
    'timestamp' : Time,
    'priority' : IDL.Nat,
  });
  const RegisteredMemberInfo = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ReportMember = IDL.Record({
    'member' : MemberProfile,
    'isExpired' : IDL.Bool,
    'moneyDue' : IDL.Nat,
    'isExpiringSoon' : IDL.Bool,
  });
  const ReportSummary = IDL.Record({
    'members' : IDL.Vec(ReportMember),
    'totalPayments' : IDL.Nat,
    'totalExpenses' : IDL.Nat,
    'profit' : IDL.Nat,
    'monthlyRevenue' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const SerializeMemberProfile = IDL.Record({
    'id' : IDL.Text,
    'principal' : IDL.Text,
    'endDate' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'membershipStatus' : MembershipStatus,
    'phone' : IDL.Text,
    'dietPlan' : IDL.Opt(DietPlan),
    'membershipPlan' : MembershipPlan,
    'profilePic' : IDL.Opt(ExternalBlob),
    'workoutPlan' : IDL.Opt(WorkoutPlan),
    'startDate' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAttendance' : IDL.Func([AttendanceRecord], [], []),
    'addClassBooking' : IDL.Func([ClassBooking], [], []),
    'addExpense' : IDL.Func([Expense], [], []),
    'addMember' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'addMemberWithManualCredentials' : IDL.Func(
        [ManualCreateMemberRequest],
        [ManualCreateMemberResponse],
        [],
      ),
    'addMembershipPlan' : IDL.Func([MembershipPlan], [], []),
    'addPayment' : IDL.Func([Payment], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkIn' : IDL.Func([], [AttendanceRecord], []),
    'checkOut' : IDL.Func([], [AttendanceRecord], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createMemberWithCredentials' : IDL.Func(
        [CreateMemberRequest],
        [CreateMemberResponse],
        [],
      ),
    'deleteMember' : IDL.Func([IDL.Nat], [], []),
    'deleteMembershipPlan' : IDL.Func([IDL.Text], [], []),
    'generateQrCode' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'getAllCommunicationLogs' : IDL.Func(
        [],
        [IDL.Vec(CommunicationLogEntry)],
        ['query'],
      ),
    'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getAllMembers' : IDL.Func([], [IDL.Vec(MemberProfile)], ['query']),
    'getAllMembershipPlans' : IDL.Func(
        [],
        [IDL.Vec(MembershipPlan)],
        ['query'],
      ),
    'getAllMinimalMembers' : IDL.Func([], [IDL.Vec(MinimalMember)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getAttendanceByMember' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceByMemberStatus' : IDL.Func(
        [MembershipStatus],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClassBookingsByStatus' : IDL.Func(
        [BookingStatus],
        [IDL.Vec(ClassBooking)],
        ['query'],
      ),
    'getCommunicationLogsByEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CommunicationLogEntry)],
        ['query'],
      ),
    'getMember' : IDL.Func([IDL.Nat], [MemberProfile], ['query']),
    'getMemberAttendance' : IDL.Func(
        [],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getMemberClassBookings' : IDL.Func([], [IDL.Vec(ClassBooking)], ['query']),
    'getMemberNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getMemberPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getMemberProfile' : IDL.Func([], [IDL.Opt(MemberProfile)], ['query']),
    'getMembershipPlan' : IDL.Func([IDL.Text], [MembershipPlan], ['query']),
    'getMyQrCode' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getPayment' : IDL.Func([IDL.Text], [Payment], ['query']),
    'getRegisteredMembers' : IDL.Func(
        [],
        [IDL.Vec(RegisteredMemberInfo)],
        ['query'],
      ),
    'getReports' : IDL.Func([], [ReportSummary], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([IDL.Principal], [UserRole], ['query']),
    'isAdminRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'logCommunication' : IDL.Func(
        [IDL.Text, CommunicationChannel, IDL.Text, CommunicationStatus],
        [],
        [],
      ),
    'memberLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [SerializeMemberProfile],
        [],
      ),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateClassBooking' : IDL.Func([IDL.Text, ClassBooking], [], []),
    'updateMember' : IDL.Func([IDL.Nat, MemberProfile], [], []),
    'updateMemberDietPlan' : IDL.Func([IDL.Nat, DietPlan], [], []),
    'updateMemberProfile' : IDL.Func([MemberProfile], [], []),
    'updateMemberWorkoutPlan' : IDL.Func([IDL.Nat, WorkoutPlan], [], []),
    'updateMembershipPlan' : IDL.Func([MembershipPlan], [], []),
    'validateQrCode' : IDL.Func([IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };