/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'Member' : null } |
  { 'Admin' : null };
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface AttendanceRecord {
  'memberId' : Principal,
  'checkInTime' : Time,
  'checkOutTime' : [] | [Time],
}
export type BookingStatus = { 'cancelled' : null } |
  { 'completed' : null } |
  { 'booked' : null };
export interface ClassBooking {
  'id' : string,
  'status' : BookingStatus,
  'memberId' : Principal,
  'date' : Time,
  'classType' : ClassType,
}
export type ClassType = { 'yoga' : null } |
  { 'crossfit' : null } |
  { 'zumba' : null } |
  { 'pilates' : null };
export type CommunicationChannel = { 'sms' : null } |
  { 'whatsapp' : null } |
  { 'email' : null };
export interface CommunicationLogEntry {
  'status' : CommunicationStatus,
  'content' : string,
  'timestamp' : Time,
  'channel' : CommunicationChannel,
}
export type CommunicationStatus = { 'pending' : null } |
  { 'sent' : null } |
  { 'failed' : null };
export interface CreateMemberRequest {
  'name' : string,
  'phone' : string,
  'membershipPlan' : MembershipPlan,
  'profilePic' : [] | [ExternalBlob],
}
export interface CreateMemberResponse {
  'member' : MemberProfile,
  'credentials' : MemberCredentials,
  'communicationLogs' : Array<CommunicationLogEntry>,
}
export interface Credentials { 'password' : string, 'email' : string }
export interface DietPlan {
  'id' : string,
  'meals' : Array<Meal>,
  'fatG' : bigint,
  'calories' : bigint,
  'name' : string,
  'description' : string,
  'carbsG' : bigint,
  'proteinG' : bigint,
}
export interface Exercise {
  'name' : string,
  'reps' : bigint,
  'sets' : bigint,
  'weightKg' : bigint,
}
export interface Expense {
  'id' : string,
  'type' : ExpenseType,
  'description' : string,
  'timestamp' : Time,
  'amount' : bigint,
}
export type ExpenseType = { 'other' : null } |
  { 'equipment' : null } |
  { 'rent' : null } |
  { 'utilities' : null };
export type ExternalBlob = Uint8Array;
export interface ManualCreateMemberRequest {
  'name' : string,
  'credentials' : Credentials,
  'phone' : string,
  'membershipPlan' : MembershipPlan,
  'profilePic' : [] | [ExternalBlob],
}
export interface ManualCreateMemberResponse {
  'member' : MemberProfile,
  'credentials' : Credentials,
  'communicationLogs' : Array<CommunicationLogEntry>,
}
export interface Meal {
  'fatG' : bigint,
  'calories' : bigint,
  'name' : string,
  'description' : string,
  'carbsG' : bigint,
  'proteinG' : bigint,
}
export interface MemberCredentials { 'password' : string, 'email' : string }
export interface MemberProfile {
  'id' : bigint,
  'principal' : Principal,
  'endDate' : Time,
  'name' : string,
  'email' : string,
  'membershipStatus' : MembershipStatus,
  'phone' : string,
  'dietPlan' : [] | [DietPlan],
  'membershipPlan' : MembershipPlan,
  'profilePic' : [] | [ExternalBlob],
  'workoutPlan' : [] | [WorkoutPlan],
  'startDate' : Time,
}
export interface MembershipPlan {
  'id' : string,
  'name' : string,
  'durationMonths' : bigint,
  'benefits' : string,
  'price' : bigint,
}
export type MembershipStatus = { 'active' : null } |
  { 'expired' : null } |
  { 'pending' : null };
export interface MinimalMember { 'id' : bigint, 'name' : string }
export interface Notification {
  'title' : string,
  'icon' : string,
  'color' : string,
  'actions' : Array<[string, string]>,
  'message' : string,
  'timestamp' : Time,
  'priority' : bigint,
}
export interface Payment {
  'id' : string,
  'status' : PaymentStatus,
  'memberId' : Principal,
  'timestamp' : Time,
  'amount' : bigint,
}
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'failed' : null };
export interface RegisteredMemberInfo {
  'id' : Principal,
  'name' : string,
  'email' : string,
  'phone' : string,
}
export interface ReportMember {
  'member' : MemberProfile,
  'isExpired' : boolean,
  'moneyDue' : bigint,
  'isExpiringSoon' : boolean,
}
export interface ReportSummary {
  'members' : Array<ReportMember>,
  'totalPayments' : bigint,
  'totalExpenses' : bigint,
  'profit' : bigint,
  'monthlyRevenue' : bigint,
}
export interface SerializeMemberProfile {
  'id' : string,
  'principal' : string,
  'endDate' : string,
  'name' : string,
  'email' : string,
  'membershipStatus' : MembershipStatus,
  'phone' : string,
  'dietPlan' : [] | [DietPlan],
  'membershipPlan' : MembershipPlan,
  'profilePic' : [] | [ExternalBlob],
  'workoutPlan' : [] | [WorkoutPlan],
  'startDate' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'id' : Principal,
  'name' : string,
  'role' : AppRole,
  'email' : string,
  'profilePic' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkoutPlan {
  'id' : string,
  'name' : string,
  'exercises' : Array<Exercise>,
  'description' : string,
  'durationWeeks' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAttendance' : ActorMethod<[AttendanceRecord], undefined>,
  'addClassBooking' : ActorMethod<[ClassBooking], undefined>,
  'addExpense' : ActorMethod<[Expense], undefined>,
  'addMember' : ActorMethod<[string], bigint>,
  'addMemberWithManualCredentials' : ActorMethod<
    [ManualCreateMemberRequest],
    ManualCreateMemberResponse
  >,
  'addMembershipPlan' : ActorMethod<[MembershipPlan], undefined>,
  'addPayment' : ActorMethod<[Payment], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkIn' : ActorMethod<[], AttendanceRecord>,
  'checkOut' : ActorMethod<[], AttendanceRecord>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createMemberWithCredentials' : ActorMethod<
    [CreateMemberRequest],
    CreateMemberResponse
  >,
  'deleteMember' : ActorMethod<[bigint], undefined>,
  'deleteMembershipPlan' : ActorMethod<[string], undefined>,
  'generateQrCode' : ActorMethod<[bigint], string>,
  'getAllCommunicationLogs' : ActorMethod<[], Array<CommunicationLogEntry>>,
  'getAllExpenses' : ActorMethod<[], Array<Expense>>,
  'getAllMembers' : ActorMethod<[], Array<MemberProfile>>,
  'getAllMembershipPlans' : ActorMethod<[], Array<MembershipPlan>>,
  'getAllMinimalMembers' : ActorMethod<[], Array<MinimalMember>>,
  'getAllPayments' : ActorMethod<[], Array<Payment>>,
  'getAttendanceByMember' : ActorMethod<[Principal], Array<AttendanceRecord>>,
  'getAttendanceByMemberStatus' : ActorMethod<
    [MembershipStatus],
    Array<AttendanceRecord>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClassBookingsByStatus' : ActorMethod<
    [BookingStatus],
    Array<ClassBooking>
  >,
  'getCommunicationLogsByEmail' : ActorMethod<
    [string],
    Array<CommunicationLogEntry>
  >,
  'getMember' : ActorMethod<[bigint], MemberProfile>,
  'getMemberAttendance' : ActorMethod<[], Array<AttendanceRecord>>,
  'getMemberClassBookings' : ActorMethod<[], Array<ClassBooking>>,
  'getMemberNotifications' : ActorMethod<[], Array<Notification>>,
  'getMemberPayments' : ActorMethod<[], Array<Payment>>,
  'getMemberProfile' : ActorMethod<[], [] | [MemberProfile]>,
  'getMembershipPlan' : ActorMethod<[string], MembershipPlan>,
  'getMyQrCode' : ActorMethod<[], [] | [string]>,
  'getPayment' : ActorMethod<[string], Payment>,
  'getRegisteredMembers' : ActorMethod<[], Array<RegisteredMemberInfo>>,
  'getReports' : ActorMethod<[], ReportSummary>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRole' : ActorMethod<[Principal], UserRole>,
  'isAdminRegistered' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'logCommunication' : ActorMethod<
    [string, CommunicationChannel, string, CommunicationStatus],
    undefined
  >,
  'memberLogin' : ActorMethod<[string, string], SerializeMemberProfile>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateClassBooking' : ActorMethod<[string, ClassBooking], undefined>,
  'updateMember' : ActorMethod<[bigint, MemberProfile], undefined>,
  'updateMemberDietPlan' : ActorMethod<[bigint, DietPlan], undefined>,
  'updateMemberProfile' : ActorMethod<[MemberProfile], undefined>,
  'updateMemberWorkoutPlan' : ActorMethod<[bigint, WorkoutPlan], undefined>,
  'updateMembershipPlan' : ActorMethod<[MembershipPlan], undefined>,
  'validateQrCode' : ActorMethod<[string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];