/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SerializeMemberProfile {
    id: string;
    principal: string;
    endDate: string;
    name: string;
    email: string;
    membershipStatus: MembershipStatus;
    phone: string;
    dietPlan?: DietPlan;
    membershipPlan: MembershipPlan;
    profilePic?: ExternalBlob;
    workoutPlan?: WorkoutPlan;
    startDate: string;
}
export interface CreateMemberRequest {
    name: string;
    phone: string;
    membershipPlan: MembershipPlan;
    profilePic?: ExternalBlob;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface RegisteredMemberInfo {
    id: Principal;
    name: string;
    email: string;
    phone: string;
}
export interface Credentials {
    password: string;
    email: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ManualCreateMemberResponse {
    member: MemberProfile;
    credentials: Credentials;
    communicationLogs: Array<CommunicationLogEntry>;
}
export interface MemberProfile {
    id: bigint;
    principal: Principal;
    endDate: Time;
    name: string;
    email: string;
    membershipStatus: MembershipStatus;
    phone: string;
    dietPlan?: DietPlan;
    membershipPlan: MembershipPlan;
    profilePic?: ExternalBlob;
    workoutPlan?: WorkoutPlan;
    startDate: Time;
}
export interface CommunicationLogEntry {
    status: CommunicationStatus;
    content: string;
    timestamp: Time;
    channel: CommunicationChannel;
}
export interface WorkoutPlan {
    id: string;
    name: string;
    exercises: Array<Exercise>;
    description: string;
    durationWeeks: bigint;
}
export interface ReportMember {
    member: MemberProfile;
    isExpired: boolean;
    moneyDue: bigint;
    isExpiringSoon: boolean;
}
export interface DietPlan {
    id: string;
    meals: Array<Meal>;
    fatG: bigint;
    calories: bigint;
    name: string;
    description: string;
    carbsG: bigint;
    proteinG: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface MinimalMember {
    id: bigint;
    name: string;
}
export interface AttendanceRecord {
    memberId: Principal;
    checkInTime: Time;
    checkOutTime?: Time;
}
export interface ManualCreateMemberRequest {
    name: string;
    credentials: Credentials;
    phone: string;
    membershipPlan: MembershipPlan;
    profilePic?: ExternalBlob;
}
export interface Meal {
    fatG: bigint;
    calories: bigint;
    name: string;
    description: string;
    carbsG: bigint;
    proteinG: bigint;
}
export interface Exercise {
    name: string;
    reps: bigint;
    sets: bigint;
    weightKg: bigint;
}
export interface CreateMemberResponse {
    member: MemberProfile;
    credentials: MemberCredentials;
    communicationLogs: Array<CommunicationLogEntry>;
}
export interface Payment {
    id: string;
    status: PaymentStatus;
    memberId: Principal;
    timestamp: Time;
    amount: bigint;
}
export interface Expense {
    id: string;
    type: ExpenseType;
    description: string;
    timestamp: Time;
    amount: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ReportSummary {
    members: Array<ReportMember>;
    totalPayments: bigint;
    totalExpenses: bigint;
    profit: bigint;
    monthlyRevenue: bigint;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface MemberCredentials {
    password: string;
    email: string;
}
export interface Notification {
    title: string;
    icon: string;
    color: string;
    actions: Array<[string, string]>;
    message: string;
    timestamp: Time;
    priority: bigint;
}
export interface MembershipPlan {
    id: string;
    name: string;
    durationMonths: bigint;
    benefits: string;
    price: bigint;
}
export interface ClassBooking {
    id: string;
    status: BookingStatus;
    memberId: Principal;
    date: Time;
    classType: ClassType;
}
export interface UserProfile {
    id: Principal;
    name: string;
    role: AppRole;
    email: string;
    profilePic?: ExternalBlob;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AppRole {
    Member = "Member",
    Admin = "Admin"
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum BookingStatus {
    cancelled = "cancelled",
    completed = "completed",
    booked = "booked"
}
export enum ClassType {
    yoga = "yoga",
    crossfit = "crossfit",
    zumba = "zumba",
    pilates = "pilates"
}
export enum CommunicationChannel {
    sms = "sms",
    whatsapp = "whatsapp",
    email = "email"
}
export enum CommunicationStatus {
    pending = "pending",
    sent = "sent",
    failed = "failed"
}
export enum ExpenseType {
    other = "other",
    equipment = "equipment",
    rent = "rent",
    utilities = "utilities"
}
export enum MembershipStatus {
    active = "active",
    expired = "expired",
    pending = "pending"
}
export enum PaymentStatus {
    pending = "pending",
    paid = "paid",
    failed = "failed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAttendance(record: AttendanceRecord): Promise<void>;
    addClassBooking(booking: ClassBooking): Promise<void>;
    addExpense(expense: Expense): Promise<void>;
    addMember(name: string): Promise<bigint>;
    addMemberWithManualCredentials(request: ManualCreateMemberRequest): Promise<ManualCreateMemberResponse>;
    addMembershipPlan(plan: MembershipPlan): Promise<void>;
    addPayment(payment: Payment): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignRole(user: Principal, role: UserRole): Promise<void>;
    checkIn(): Promise<AttendanceRecord>;
    checkOut(): Promise<AttendanceRecord>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createMemberWithCredentials(arg0: CreateMemberRequest): Promise<CreateMemberResponse>;
    deleteMember(id: bigint): Promise<void>;
    deleteMembershipPlan(id: string): Promise<void>;
    generateQrCode(memberId: bigint): Promise<string>;
    getAllCommunicationLogs(): Promise<Array<CommunicationLogEntry>>;
    getAllExpenses(): Promise<Array<Expense>>;
    getAllMembers(): Promise<Array<MemberProfile>>;
    getAllMembershipPlans(): Promise<Array<MembershipPlan>>;
    getAllMinimalMembers(): Promise<Array<MinimalMember>>;
    getAllPayments(): Promise<Array<Payment>>;
    getAttendanceByMember(memberId: Principal): Promise<Array<AttendanceRecord>>;
    getAttendanceByMemberStatus(memberStatus: MembershipStatus): Promise<Array<AttendanceRecord>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClassBookingsByStatus(status: BookingStatus): Promise<Array<ClassBooking>>;
    getCommunicationLogsByEmail(email: string): Promise<Array<CommunicationLogEntry>>;
    getMember(id: bigint): Promise<MemberProfile>;
    getMemberAttendance(): Promise<Array<AttendanceRecord>>;
    getMemberClassBookings(): Promise<Array<ClassBooking>>;
    getMemberNotifications(): Promise<Array<Notification>>;
    getMemberPayments(): Promise<Array<Payment>>;
    getMemberProfile(): Promise<MemberProfile | null>;
    getMembershipPlan(id: string): Promise<MembershipPlan>;
    getMyQrCode(): Promise<string | null>;
    getPayment(id: string): Promise<Payment>;
    getRegisteredMembers(): Promise<Array<RegisteredMemberInfo>>;
    getReports(): Promise<ReportSummary>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserRole(target: Principal): Promise<UserRole>;
    isAdminRegistered(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    logCommunication(to: string, channel: CommunicationChannel, content: string, status: CommunicationStatus): Promise<void>;
    memberLogin(email: string, password: string): Promise<SerializeMemberProfile>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateClassBooking(id: string, booking: ClassBooking): Promise<void>;
    updateMember(id: bigint, member: MemberProfile): Promise<void>;
    updateMemberDietPlan(memberId: bigint, plan: DietPlan): Promise<void>;
    updateMemberProfile(profile: MemberProfile): Promise<void>;
    updateMemberWorkoutPlan(memberId: bigint, plan: WorkoutPlan): Promise<void>;
    updateMembershipPlan(plan: MembershipPlan): Promise<void>;
    validateQrCode(qr: string): Promise<bigint>;
}
import type { AppRole as _AppRole, ApprovalStatus as _ApprovalStatus, AttendanceRecord as _AttendanceRecord, BookingStatus as _BookingStatus, ClassBooking as _ClassBooking, ClassType as _ClassType, CommunicationChannel as _CommunicationChannel, CommunicationLogEntry as _CommunicationLogEntry, CommunicationStatus as _CommunicationStatus, CreateMemberRequest as _CreateMemberRequest, CreateMemberResponse as _CreateMemberResponse, Credentials as _Credentials, DietPlan as _DietPlan, Expense as _Expense, ExpenseType as _ExpenseType, ExternalBlob as _ExternalBlob, ManualCreateMemberRequest as _ManualCreateMemberRequest, ManualCreateMemberResponse as _ManualCreateMemberResponse, MemberCredentials as _MemberCredentials, MemberProfile as _MemberProfile, MembershipPlan as _MembershipPlan, MembershipStatus as _MembershipStatus, Payment as _Payment, PaymentStatus as _PaymentStatus, ReportMember as _ReportMember, ReportSummary as _ReportSummary, SerializeMemberProfile as _SerializeMemberProfile, StripeSessionStatus as _StripeSessionStatus, Time as _Time, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, WorkoutPlan as _WorkoutPlan, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAttendance(arg0: AttendanceRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAttendance(to_candid_AttendanceRecord_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAttendance(to_candid_AttendanceRecord_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addClassBooking(arg0: ClassBooking): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addClassBooking(to_candid_ClassBooking_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClassBooking(to_candid_ClassBooking_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addExpense(arg0: Expense): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(to_candid_Expense_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(to_candid_Expense_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addMember(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMember(arg0);
            return result;
        }
    }
    async addMemberWithManualCredentials(arg0: ManualCreateMemberRequest): Promise<ManualCreateMemberResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.addMemberWithManualCredentials(await to_candid_ManualCreateMemberRequest_n20(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ManualCreateMemberResponse_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMemberWithManualCredentials(await to_candid_ManualCreateMemberRequest_n20(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ManualCreateMemberResponse_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async addMembershipPlan(arg0: MembershipPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMembershipPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMembershipPlan(arg0);
            return result;
        }
    }
    async addPayment(arg0: Payment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPayment(to_candid_Payment_n40(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPayment(to_candid_Payment_n40(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n44(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n44(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRole(arg0, to_candid_UserRole_n44(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRole(arg0, to_candid_UserRole_n44(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkIn(): Promise<AttendanceRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.checkIn();
                return from_candid_AttendanceRecord_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkIn();
            return from_candid_AttendanceRecord_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async checkOut(): Promise<AttendanceRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.checkOut();
                return from_candid_AttendanceRecord_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkOut();
            return from_candid_AttendanceRecord_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createMemberWithCredentials(arg0: CreateMemberRequest): Promise<CreateMemberResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.createMemberWithCredentials(await to_candid_CreateMemberRequest_n49(this._uploadFile, this._downloadFile, arg0));
                return from_candid_CreateMemberResponse_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMemberWithCredentials(await to_candid_CreateMemberRequest_n49(this._uploadFile, this._downloadFile, arg0));
            return from_candid_CreateMemberResponse_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteMember(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMember(arg0);
            return result;
        }
    }
    async deleteMembershipPlan(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMembershipPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMembershipPlan(arg0);
            return result;
        }
    }
    async generateQrCode(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateQrCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateQrCode(arg0);
            return result;
        }
    }
    async getAllCommunicationLogs(): Promise<Array<CommunicationLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCommunicationLogs();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCommunicationLogs();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllExpenses(): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExpenses();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExpenses();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMembers(): Promise<Array<MemberProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMembers();
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMembers();
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMembershipPlans(): Promise<Array<MembershipPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMembershipPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMembershipPlans();
            return result;
        }
    }
    async getAllMinimalMembers(): Promise<Array<MinimalMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMinimalMembers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMinimalMembers();
            return result;
        }
    }
    async getAllPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPayments();
                return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPayments();
            return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceByMember(arg0: Principal): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByMember(arg0);
                return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByMember(arg0);
            return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceByMemberStatus(arg0: MembershipStatus): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByMemberStatus(to_candid_MembershipStatus_n65(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByMemberStatus(to_candid_MembershipStatus_n65(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n72(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n72(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClassBookingsByStatus(arg0: BookingStatus): Promise<Array<ClassBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClassBookingsByStatus(to_candid_BookingStatus_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n74(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClassBookingsByStatus(to_candid_BookingStatus_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n74(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommunicationLogsByEmail(arg0: string): Promise<Array<CommunicationLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommunicationLogsByEmail(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommunicationLogsByEmail(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMember(arg0: bigint): Promise<MemberProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getMember(arg0);
                return from_candid_MemberProfile_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMember(arg0);
            return from_candid_MemberProfile_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMemberAttendance(): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemberAttendance();
                return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemberAttendance();
            return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMemberClassBookings(): Promise<Array<ClassBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemberClassBookings();
                return from_candid_vec_n74(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemberClassBookings();
            return from_candid_vec_n74(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMemberNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemberNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemberNotifications();
            return result;
        }
    }
    async getMemberPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemberPayments();
                return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemberPayments();
            return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMemberProfile(): Promise<MemberProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemberProfile();
                return from_candid_opt_n81(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemberProfile();
            return from_candid_opt_n81(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMembershipPlan(arg0: string): Promise<MembershipPlan> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembershipPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembershipPlan(arg0);
            return result;
        }
    }
    async getMyQrCode(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyQrCode();
                return from_candid_opt_n82(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyQrCode();
            return from_candid_opt_n82(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayment(arg0: string): Promise<Payment> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayment(arg0);
                return from_candid_Payment_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayment(arg0);
            return from_candid_Payment_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRegisteredMembers(): Promise<Array<RegisteredMemberInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegisteredMembers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegisteredMembers();
            return result;
        }
    }
    async getReports(): Promise<ReportSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getReports();
                return from_candid_ReportSummary_n83(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReports();
            return from_candid_ReportSummary_n83(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n88(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n88(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRole(arg0: Principal): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRole(arg0);
                return from_candid_UserRole_n72(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRole(arg0);
            return from_candid_UserRole_n72(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdminRegistered(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminRegistered();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminRegistered();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n91(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n91(this._uploadFile, this._downloadFile, result);
        }
    }
    async logCommunication(arg0: string, arg1: CommunicationChannel, arg2: string, arg3: CommunicationStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logCommunication(arg0, to_candid_CommunicationChannel_n96(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_CommunicationStatus_n98(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logCommunication(arg0, to_candid_CommunicationChannel_n96(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_CommunicationStatus_n98(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async memberLogin(arg0: string, arg1: string): Promise<SerializeMemberProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.memberLogin(arg0, arg1);
                return from_candid_SerializeMemberProfile_n100(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.memberLogin(arg0, arg1);
            return from_candid_SerializeMemberProfile_n100(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n102(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n102(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n106(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n106(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateClassBooking(arg0: string, arg1: ClassBooking): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClassBooking(arg0, to_candid_ClassBooking_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClassBooking(arg0, to_candid_ClassBooking_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMember(arg0: bigint, arg1: MemberProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMember(arg0, await to_candid_MemberProfile_n108(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMember(arg0, await to_candid_MemberProfile_n108(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMemberDietPlan(arg0: bigint, arg1: DietPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMemberDietPlan(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMemberDietPlan(arg0, arg1);
            return result;
        }
    }
    async updateMemberProfile(arg0: MemberProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMemberProfile(await to_candid_MemberProfile_n108(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMemberProfile(await to_candid_MemberProfile_n108(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateMemberWorkoutPlan(arg0: bigint, arg1: WorkoutPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMemberWorkoutPlan(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMemberWorkoutPlan(arg0, arg1);
            return result;
        }
    }
    async updateMembershipPlan(arg0: MembershipPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMembershipPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMembershipPlan(arg0);
            return result;
        }
    }
    async validateQrCode(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.validateQrCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateQrCode(arg0);
            return result;
        }
    }
}
function from_candid_AppRole_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppRole): AppRole {
    return from_candid_variant_n71(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n94(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n95(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceRecord_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceRecord): AttendanceRecord {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n78(_uploadFile, _downloadFile, value);
}
function from_candid_ClassBooking_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClassBooking): ClassBooking {
    return from_candid_record_n76(_uploadFile, _downloadFile, value);
}
function from_candid_ClassType_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClassType): ClassType {
    return from_candid_variant_n80(_uploadFile, _downloadFile, value);
}
function from_candid_CommunicationChannel_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommunicationChannel): CommunicationChannel {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_CommunicationLogEntry_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommunicationLogEntry): CommunicationLogEntry {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_CommunicationStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommunicationStatus): CommunicationStatus {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
async function from_candid_CreateMemberResponse_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreateMemberResponse): Promise<CreateMemberResponse> {
    return await from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_ExpenseType_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExpenseType): ExpenseType {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_Expense_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Expense): Expense {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_ManualCreateMemberResponse_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ManualCreateMemberResponse): Promise<ManualCreateMemberResponse> {
    return await from_candid_record_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_MemberProfile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemberProfile): Promise<MemberProfile> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_MembershipStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MembershipStatus): MembershipStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n61(_uploadFile, _downloadFile, value);
}
async function from_candid_ReportMember_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportMember): Promise<ReportMember> {
    return await from_candid_record_n87(_uploadFile, _downloadFile, value);
}
async function from_candid_ReportSummary_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportSummary): Promise<ReportSummary> {
    return await from_candid_record_n84(_uploadFile, _downloadFile, value);
}
async function from_candid_SerializeMemberProfile_n100(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SerializeMemberProfile): Promise<SerializeMemberProfile> {
    return await from_candid_record_n101(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n89(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n93(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n69(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n73(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DietPlan]): DietPlan | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WorkoutPlan]): WorkoutPlan | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n68(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MemberProfile]): Promise<MemberProfile | null> {
    return value.length === 0 ? null : await from_candid_MemberProfile_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n101(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    principal: string;
    endDate: string;
    name: string;
    email: string;
    membershipStatus: _MembershipStatus;
    phone: string;
    dietPlan: [] | [_DietPlan];
    membershipPlan: _MembershipPlan;
    profilePic: [] | [_ExternalBlob];
    workoutPlan: [] | [_WorkoutPlan];
    startDate: string;
}): Promise<{
    id: string;
    principal: string;
    endDate: string;
    name: string;
    email: string;
    membershipStatus: MembershipStatus;
    phone: string;
    dietPlan?: DietPlan;
    membershipPlan: MembershipPlan;
    profilePic?: ExternalBlob;
    workoutPlan?: WorkoutPlan;
    startDate: string;
}> {
    return {
        id: value.id,
        principal: value.principal,
        endDate: value.endDate,
        name: value.name,
        email: value.email,
        membershipStatus: from_candid_MembershipStatus_n27(_uploadFile, _downloadFile, value.membershipStatus),
        phone: value.phone,
        dietPlan: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.dietPlan)),
        membershipPlan: value.membershipPlan,
        profilePic: record_opt_to_undefined(await from_candid_opt_n30(_uploadFile, _downloadFile, value.profilePic)),
        workoutPlan: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.workoutPlan)),
        startDate: value.startDate
    };
}
async function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    member: _MemberProfile;
    credentials: _Credentials;
    communicationLogs: Array<_CommunicationLogEntry>;
}): Promise<{
    member: MemberProfile;
    credentials: Credentials;
    communicationLogs: Array<CommunicationLogEntry>;
}> {
    return {
        member: await from_candid_MemberProfile_n25(_uploadFile, _downloadFile, value.member),
        credentials: value.credentials,
        communicationLogs: from_candid_vec_n33(_uploadFile, _downloadFile, value.communicationLogs)
    };
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    principal: Principal;
    endDate: _Time;
    name: string;
    email: string;
    membershipStatus: _MembershipStatus;
    phone: string;
    dietPlan: [] | [_DietPlan];
    membershipPlan: _MembershipPlan;
    profilePic: [] | [_ExternalBlob];
    workoutPlan: [] | [_WorkoutPlan];
    startDate: _Time;
}): Promise<{
    id: bigint;
    principal: Principal;
    endDate: Time;
    name: string;
    email: string;
    membershipStatus: MembershipStatus;
    phone: string;
    dietPlan?: DietPlan;
    membershipPlan: MembershipPlan;
    profilePic?: ExternalBlob;
    workoutPlan?: WorkoutPlan;
    startDate: Time;
}> {
    return {
        id: value.id,
        principal: value.principal,
        endDate: value.endDate,
        name: value.name,
        email: value.email,
        membershipStatus: from_candid_MembershipStatus_n27(_uploadFile, _downloadFile, value.membershipStatus),
        phone: value.phone,
        dietPlan: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.dietPlan)),
        membershipPlan: value.membershipPlan,
        profilePic: record_opt_to_undefined(await from_candid_opt_n30(_uploadFile, _downloadFile, value.profilePic)),
        workoutPlan: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.workoutPlan)),
        startDate: value.startDate
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _CommunicationStatus;
    content: string;
    timestamp: _Time;
    channel: _CommunicationChannel;
}): {
    status: CommunicationStatus;
    content: string;
    timestamp: Time;
    channel: CommunicationChannel;
} {
    return {
        status: from_candid_CommunicationStatus_n36(_uploadFile, _downloadFile, value.status),
        content: value.content,
        timestamp: value.timestamp,
        channel: from_candid_CommunicationChannel_n38(_uploadFile, _downloadFile, value.channel)
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    memberId: Principal;
    checkInTime: _Time;
    checkOutTime: [] | [_Time];
}): {
    memberId: Principal;
    checkInTime: Time;
    checkOutTime?: Time;
} {
    return {
        memberId: value.memberId,
        checkInTime: value.checkInTime,
        checkOutTime: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.checkOutTime))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    member: _MemberProfile;
    credentials: _MemberCredentials;
    communicationLogs: Array<_CommunicationLogEntry>;
}): Promise<{
    member: MemberProfile;
    credentials: MemberCredentials;
    communicationLogs: Array<CommunicationLogEntry>;
}> {
    return {
        member: await from_candid_MemberProfile_n25(_uploadFile, _downloadFile, value.member),
        credentials: value.credentials,
        communicationLogs: from_candid_vec_n33(_uploadFile, _downloadFile, value.communicationLogs)
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    type: _ExpenseType;
    description: string;
    timestamp: _Time;
    amount: bigint;
}): {
    id: string;
    type: ExpenseType;
    description: string;
    timestamp: Time;
    amount: bigint;
} {
    return {
        id: value.id,
        type: from_candid_ExpenseType_n56(_uploadFile, _downloadFile, value.type),
        description: value.description,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _PaymentStatus;
    memberId: Principal;
    timestamp: _Time;
    amount: bigint;
}): {
    id: string;
    status: PaymentStatus;
    memberId: Principal;
    timestamp: Time;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_PaymentStatus_n62(_uploadFile, _downloadFile, value.status),
        memberId: value.memberId,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
async function from_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    name: string;
    role: _AppRole;
    email: string;
    profilePic: [] | [_ExternalBlob];
}): Promise<{
    id: Principal;
    name: string;
    role: AppRole;
    email: string;
    profilePic?: ExternalBlob;
}> {
    return {
        id: value.id,
        name: value.name,
        role: from_candid_AppRole_n70(_uploadFile, _downloadFile, value.role),
        email: value.email,
        profilePic: record_opt_to_undefined(await from_candid_opt_n30(_uploadFile, _downloadFile, value.profilePic))
    };
}
function from_candid_record_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _BookingStatus;
    memberId: Principal;
    date: _Time;
    classType: _ClassType;
}): {
    id: string;
    status: BookingStatus;
    memberId: Principal;
    date: Time;
    classType: ClassType;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n77(_uploadFile, _downloadFile, value.status),
        memberId: value.memberId,
        date: value.date,
        classType: from_candid_ClassType_n79(_uploadFile, _downloadFile, value.classType)
    };
}
async function from_candid_record_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    members: Array<_ReportMember>;
    totalPayments: bigint;
    totalExpenses: bigint;
    profit: bigint;
    monthlyRevenue: bigint;
}): Promise<{
    members: Array<ReportMember>;
    totalPayments: bigint;
    totalExpenses: bigint;
    profit: bigint;
    monthlyRevenue: bigint;
}> {
    return {
        members: await from_candid_vec_n85(_uploadFile, _downloadFile, value.members),
        totalPayments: value.totalPayments,
        totalExpenses: value.totalExpenses,
        profit: value.profit,
        monthlyRevenue: value.monthlyRevenue
    };
}
async function from_candid_record_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    member: _MemberProfile;
    isExpired: boolean;
    moneyDue: bigint;
    isExpiringSoon: boolean;
}): Promise<{
    member: MemberProfile;
    isExpired: boolean;
    moneyDue: bigint;
    isExpiringSoon: boolean;
}> {
    return {
        member: await from_candid_MemberProfile_n25(_uploadFile, _downloadFile, value.member),
        isExpired: value.isExpired,
        moneyDue: value.moneyDue,
        isExpiringSoon: value.isExpiringSoon
    };
}
function from_candid_record_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n82(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n94(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    expired: null;
} | {
    pending: null;
}): MembershipStatus {
    return "active" in value ? MembershipStatus.active : "expired" in value ? MembershipStatus.expired : "pending" in value ? MembershipStatus.pending : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    sent: null;
} | {
    failed: null;
}): CommunicationStatus {
    return "pending" in value ? CommunicationStatus.pending : "sent" in value ? CommunicationStatus.sent : "failed" in value ? CommunicationStatus.failed : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sms: null;
} | {
    whatsapp: null;
} | {
    email: null;
}): CommunicationChannel {
    return "sms" in value ? CommunicationChannel.sms : "whatsapp" in value ? CommunicationChannel.whatsapp : "email" in value ? CommunicationChannel.email : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    equipment: null;
} | {
    rent: null;
} | {
    utilities: null;
}): ExpenseType {
    return "other" in value ? ExpenseType.other : "equipment" in value ? ExpenseType.equipment : "rent" in value ? ExpenseType.rent : "utilities" in value ? ExpenseType.utilities : value;
}
function from_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "paid" in value ? PaymentStatus.paid : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_variant_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Member: null;
} | {
    Admin: null;
}): AppRole {
    return "Member" in value ? AppRole.Member : "Admin" in value ? AppRole.Admin : value;
}
function from_candid_variant_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    completed: null;
} | {
    booked: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "completed" in value ? BookingStatus.completed : "booked" in value ? BookingStatus.booked : value;
}
function from_candid_variant_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    yoga: null;
} | {
    crossfit: null;
} | {
    zumba: null;
} | {
    pilates: null;
}): ClassType {
    return "yoga" in value ? ClassType.yoga : "crossfit" in value ? ClassType.crossfit : "zumba" in value ? ClassType.zumba : "pilates" in value ? ClassType.pilates : value;
}
function from_candid_variant_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n90(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n95(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CommunicationLogEntry>): Array<CommunicationLogEntry> {
    return value.map((x)=>from_candid_CommunicationLogEntry_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Expense>): Array<Expense> {
    return value.map((x)=>from_candid_Expense_n54(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MemberProfile>): Promise<Array<MemberProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_MemberProfile_n25(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n60(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceRecord>): Array<AttendanceRecord> {
    return value.map((x)=>from_candid_AttendanceRecord_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClassBooking>): Array<ClassBooking> {
    return value.map((x)=>from_candid_ClassBooking_n75(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ReportMember>): Promise<Array<ReportMember>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ReportMember_n86(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n92(_uploadFile, _downloadFile, x));
}
function to_candid_AppRole_n104(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): _AppRole {
    return to_candid_variant_n105(_uploadFile, _downloadFile, value);
}
function to_candid_ApprovalStatus_n106(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n107(_uploadFile, _downloadFile, value);
}
function to_candid_AttendanceRecord_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceRecord): _AttendanceRecord {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_BookingStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_ClassBooking_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClassBooking): _ClassBooking {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_ClassType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClassType): _ClassType {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_CommunicationChannel_n96(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CommunicationChannel): _CommunicationChannel {
    return to_candid_variant_n97(_uploadFile, _downloadFile, value);
}
function to_candid_CommunicationStatus_n98(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CommunicationStatus): _CommunicationStatus {
    return to_candid_variant_n99(_uploadFile, _downloadFile, value);
}
async function to_candid_CreateMemberRequest_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateMemberRequest): Promise<_CreateMemberRequest> {
    return await to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_ExpenseType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseType): _ExpenseType {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_Expense_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Expense): _Expense {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_ManualCreateMemberRequest_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ManualCreateMemberRequest): Promise<_ManualCreateMemberRequest> {
    return await to_candid_record_n21(_uploadFile, _downloadFile, value);
}
async function to_candid_MemberProfile_n108(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberProfile): Promise<_MemberProfile> {
    return await to_candid_record_n109(_uploadFile, _downloadFile, value);
}
function to_candid_MembershipStatus_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MembershipStatus): _MembershipStatus {
    return to_candid_variant_n66(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid_Payment_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Payment): _Payment {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n102(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n103(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n103(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    name: string;
    role: AppRole;
    email: string;
    profilePic?: ExternalBlob;
}): Promise<{
    id: Principal;
    name: string;
    role: _AppRole;
    email: string;
    profilePic: [] | [_ExternalBlob];
}> {
    return {
        id: value.id,
        name: value.name,
        role: to_candid_AppRole_n104(_uploadFile, _downloadFile, value.role),
        email: value.email,
        profilePic: value.profilePic ? candid_some(await to_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.profilePic)) : candid_none()
    };
}
async function to_candid_record_n109(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    principal: Principal;
    endDate: Time;
    name: string;
    email: string;
    membershipStatus: MembershipStatus;
    phone: string;
    dietPlan?: DietPlan;
    membershipPlan: MembershipPlan;
    profilePic?: ExternalBlob;
    workoutPlan?: WorkoutPlan;
    startDate: Time;
}): Promise<{
    id: bigint;
    principal: Principal;
    endDate: _Time;
    name: string;
    email: string;
    membershipStatus: _MembershipStatus;
    phone: string;
    dietPlan: [] | [_DietPlan];
    membershipPlan: _MembershipPlan;
    profilePic: [] | [_ExternalBlob];
    workoutPlan: [] | [_WorkoutPlan];
    startDate: _Time;
}> {
    return {
        id: value.id,
        principal: value.principal,
        endDate: value.endDate,
        name: value.name,
        email: value.email,
        membershipStatus: to_candid_MembershipStatus_n65(_uploadFile, _downloadFile, value.membershipStatus),
        phone: value.phone,
        dietPlan: value.dietPlan ? candid_some(value.dietPlan) : candid_none(),
        membershipPlan: value.membershipPlan,
        profilePic: value.profilePic ? candid_some(await to_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.profilePic)) : candid_none(),
        workoutPlan: value.workoutPlan ? candid_some(value.workoutPlan) : candid_none(),
        startDate: value.startDate
    };
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: BookingStatus;
    memberId: Principal;
    date: Time;
    classType: ClassType;
}): {
    id: string;
    status: _BookingStatus;
    memberId: Principal;
    date: _Time;
    classType: _ClassType;
} {
    return {
        id: value.id,
        status: to_candid_BookingStatus_n12(_uploadFile, _downloadFile, value.status),
        memberId: value.memberId,
        date: value.date,
        classType: to_candid_ClassType_n14(_uploadFile, _downloadFile, value.classType)
    };
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    type: ExpenseType;
    description: string;
    timestamp: Time;
    amount: bigint;
}): {
    id: string;
    type: _ExpenseType;
    description: string;
    timestamp: _Time;
    amount: bigint;
} {
    return {
        id: value.id,
        type: to_candid_ExpenseType_n18(_uploadFile, _downloadFile, value.type),
        description: value.description,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
async function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    credentials: Credentials;
    phone: string;
    membershipPlan: MembershipPlan;
    profilePic?: ExternalBlob;
}): Promise<{
    name: string;
    credentials: _Credentials;
    phone: string;
    membershipPlan: _MembershipPlan;
    profilePic: [] | [_ExternalBlob];
}> {
    return {
        name: value.name,
        credentials: value.credentials,
        phone: value.phone,
        membershipPlan: value.membershipPlan,
        profilePic: value.profilePic ? candid_some(await to_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.profilePic)) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: PaymentStatus;
    memberId: Principal;
    timestamp: Time;
    amount: bigint;
}): {
    id: string;
    status: _PaymentStatus;
    memberId: Principal;
    timestamp: _Time;
    amount: bigint;
} {
    return {
        id: value.id,
        status: to_candid_PaymentStatus_n42(_uploadFile, _downloadFile, value.status),
        memberId: value.memberId,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
async function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    phone: string;
    membershipPlan: MembershipPlan;
    profilePic?: ExternalBlob;
}): Promise<{
    name: string;
    phone: string;
    membershipPlan: _MembershipPlan;
    profilePic: [] | [_ExternalBlob];
}> {
    return {
        name: value.name,
        phone: value.phone,
        membershipPlan: value.membershipPlan,
        profilePic: value.profilePic ? candid_some(await to_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.profilePic)) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    memberId: Principal;
    checkInTime: Time;
    checkOutTime?: Time;
}): {
    memberId: Principal;
    checkInTime: _Time;
    checkOutTime: [] | [_Time];
} {
    return {
        memberId: value.memberId,
        checkInTime: value.checkInTime,
        checkOutTime: value.checkOutTime ? candid_some(value.checkOutTime) : candid_none()
    };
}
function to_candid_variant_n105(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): {
    Member: null;
} | {
    Admin: null;
} {
    return value == AppRole.Member ? {
        Member: null
    } : value == AppRole.Admin ? {
        Admin: null
    } : value;
}
function to_candid_variant_n107(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    cancelled: null;
} | {
    completed: null;
} | {
    booked: null;
} {
    return value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.completed ? {
        completed: null
    } : value == BookingStatus.booked ? {
        booked: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClassType): {
    yoga: null;
} | {
    crossfit: null;
} | {
    zumba: null;
} | {
    pilates: null;
} {
    return value == ClassType.yoga ? {
        yoga: null
    } : value == ClassType.crossfit ? {
        crossfit: null
    } : value == ClassType.zumba ? {
        zumba: null
    } : value == ClassType.pilates ? {
        pilates: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseType): {
    other: null;
} | {
    equipment: null;
} | {
    rent: null;
} | {
    utilities: null;
} {
    return value == ExpenseType.other ? {
        other: null
    } : value == ExpenseType.equipment ? {
        equipment: null
    } : value == ExpenseType.rent ? {
        rent: null
    } : value == ExpenseType.utilities ? {
        utilities: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    pending: null;
} | {
    paid: null;
} | {
    failed: null;
} {
    return value == PaymentStatus.pending ? {
        pending: null
    } : value == PaymentStatus.paid ? {
        paid: null
    } : value == PaymentStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MembershipStatus): {
    active: null;
} | {
    expired: null;
} | {
    pending: null;
} {
    return value == MembershipStatus.active ? {
        active: null
    } : value == MembershipStatus.expired ? {
        expired: null
    } : value == MembershipStatus.pending ? {
        pending: null
    } : value;
}
function to_candid_variant_n97(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CommunicationChannel): {
    sms: null;
} | {
    whatsapp: null;
} | {
    email: null;
} {
    return value == CommunicationChannel.sms ? {
        sms: null
    } : value == CommunicationChannel.whatsapp ? {
        whatsapp: null
    } : value == CommunicationChannel.email ? {
        email: null
    } : value;
}
function to_candid_variant_n99(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CommunicationStatus): {
    pending: null;
} | {
    sent: null;
} | {
    failed: null;
} {
    return value == CommunicationStatus.pending ? {
        pending: null
    } : value == CommunicationStatus.sent ? {
        sent: null
    } : value == CommunicationStatus.failed ? {
        failed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
